"""empty message

Revision ID: 327984579f45
Revises: fa0303a055f4
Create Date: 2025-07-04 19:19:52.364993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327984579f45'
down_revision = 'fa0303a055f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_planets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planet_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
